[[sect:namespaces]]
== Modules and Namespaces

An [logo]#Idris# program consists of a collection of modules.
Each module includes an optional `module` declaration giving the name of the module, a list of `import` statements giving the other modules which are to be imported, and a collection of declarations and definitions of types, classes and functions.
For example, <<bstmod>> gives a module which defines a binary tree type `BTree` (in a file `btree.idr`) and <<bstmain>> gives a main program (in a file `bmain.idr` which uses the `bst` module to sort a list.

[[bstmod]]
[source, idris]
.Listing 2: Binary Tree Module
----
include::{sourcedir}/btree.idr[]
----

[[bstmain]]
[source, idris]
.Listing 3: Binary Tree Main Program
----
include::{sourcedir}/bmain.idr[]
----


The same names can be defined in multiple modules.
This is possible because in practice names are _qualified_ with the name of the module.
The names defined in the `btree` module are, in full:

[cols="2",frame="none",grid="none"]
|===
a|
* `btree.BTree`,
* `btree.Leaf`,
* `btree.Node`,
a|
* `btree.insert`,
* `btree.toList`,
* `btree.toTree`.
|===

If names are otherwise unambiguous, there is no need to give the fully qualified name.
Names can be disambiguated either by giving an explicit qualification, or according to their type.

There is no formal link between the module name and its filename, although it is generally advisable to use the same name for each.
An `import` statement refers to a filename, using dots to separate directories.
For example, `import foo.bar` would import the file `foo/bar.idr`, which would conventionally have the module declaration `module foo.bar`.
The only requirement for module names is that the main module, with the `main` function, must be called `Main`—although its filename need not be `Main.idr`.

[[export-modifiers]]
=== Export Modifiers

By default, all names defined in a module are exported for use by other modules.
However, it is good practice only to export a minimal interface and keep internal details abstract.
[logo]#Idris# allows functions, types, and classes to be marked as: `public`, `abstract` or `private`:

* `public` means that both the name and definition are exported.
For functions, this means that the implementation is exported (which means, for example, it can be used in a dependent type).
For data types, this means that the type name and the constructors are exported.
For classes, this means that the class name and method names are exported.
* `abstract` means that only the name is exported.
For functions, this means that the implementation is not exported.
For data types, this means that the type name is exported but not the constructors.
For classes, this means that the class name is exported but not the method names.
* `private` means that neither the name nor the definition is exported.

*Note:* If any definition is given an export modifier, then all names with no modifier are assumed to be `private`.

For our `btree` module, it makes sense for the tree data type and the functions to be exported as `abstract`, as we see in <<bstmodp>>.

[[bstmodp]]
[source, idris]
.Listing 4: Binary Tree Module, with export modifiers
----
include::{sourcedir}/btreemod.idr[]
----

Finally, the default export mode can be changed with the `%access` directive, for example:

----
%access abstract
----

In this case, any function with no access modifier will be exported as `abstract`, rather than left `private`.

Additionally, a module can re-export a module it has imported, by using the `public` modifier on an `import`.
For example:

----
module A

import B
import public C

public a : AType
a = ...
----

The module `A` will export the name `a`, as well as any public or abstract names in module `C`, but will not re-export anything from module `B`.

[[explicit-namespaces]]
=== Explicit Namespaces

Defining a module also defines a namespace implicitly.
However, namespaces can also be given _explicitly_.
This is most useful if you wish to overload names within the same module:

[source, idris]
----
include::{sourcedir}/foo.idr[]
----

This (admittedly contrived) module defines two functions with fully qualified names `foo.x.test` and `foo.y.test`, which can be disambiguated by their types:

----
*foo> test 3
6 : Int
*foo> test "foo"
"foofoo" : String
----

[[parameterised-blocks]]
=== Parameterised blocks

Groups of functions can be parameterised over a number of arguments using a `parameters` declaration, for example:

----
parameters (x : Nat, y : Nat)
    addAll : Nat -> Nat
    addAll z = x + y + z
----

The effect of a `parameters` block is to add the declared parameters to every function, type and data constructor within the block.
Outside the block, the parameters must be given explicitly:

----
*params> :t addAll
addAll : Nat -> Nat -> Nat -> Nat
----

Parameters blocks can be nested, and can also include data declarations, in which case the parameters are added explicitly to all type and data constructors.
They may also be dependent types with implicit arguments:

----
parameters (y : Nat, xs : Vect x a)
    data Vects : Type -> Type where
         MkVects : Vect y a -> Vects a

    append : Vects a -> Vect (x + y) a
    append (MkVects ys) = xs ++ ys
----

To use `Vects` or `append` outside the block, we must also give the `xs` and `y` arguments.
Here, we can use placeholders for the values which can be inferred by the type checker:

----
*params> show (append _ _ (MkVects _ [1,2,3] [4,5,6]))
"[1, 2, 3, 4, 5, 6]" : String
----
